# Generated by Django 4.1.3 on 2022-11-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofc',
            name='name',
        ),
        migrations.AddField(
            model_name='ofc',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Адрес'),
        ),
    ]
