# Generated by Django 4.1.3 on 2022-11-10 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_ofc_name_ofc_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizenship',
            options={'ordering': ['-pk'], 'verbose_name': 'Гражданство', 'verbose_name_plural': 'Гражданства'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='название города'),
        ),
        migrations.AlterField(
            model_name='ofc',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofcs', to='app.city', verbose_name='Город'),
        ),
    ]
