# Generated by Django 4.1.3 on 2022-11-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_citizenship_options_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
