# Generated by Django 4.1.3 on 2022-11-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_salaryfile_profile_password_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='password',
            new_name='password1',
        ),
    ]
