# Generated by Django 4.1.3 on 2022-11-12 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_rename_password_profile_password1'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.AddField(
            model_name='executor',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='executors', to='app.transport', verbose_name='Транспорт'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='code',
            field=models.CharField(max_length=256, unique=True, verbose_name='Код велосипеда'),
        ),
    ]
