# Generated by Django 4.1.3 on 2022-11-12 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_executor_curator_executor_transport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='executors', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
    ]
