# Generated by Django 4.1.3 on 2022-11-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_executor_code_alter_executor_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofc',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Код'),
        ),
    ]
