# Generated by Django 4.1.3 on 2022-11-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ofc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='executors', to='app.citizenship', verbose_name='Гражданство'),
        ),
    ]
