# Generated by Django 4.1.3 on 2022-11-13 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_executor_citizenship'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип гражданства',
                'verbose_name_plural': 'Типы гражданства',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='executor',
            name='citizenship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='executors', to='app.citizenshiptype', verbose_name='Тип гражданства'),
        ),
    ]
