# Generated by Django 4.1.3 on 2022-11-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_citizenshiptype_executor_citizenship_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofc',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Адрес'),
        ),
    ]
