# Generated by Django 4.1.3 on 2022-11-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_ofc_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofc',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
