# Generated by Django 4.1.3 on 2022-11-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_ofc_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='archive_files', verbose_name='Файл')),
                ('type', models.CharField(blank=True, choices=[('salary', 'Зарплата'), ('executor', 'Исполнитель'), ('city', 'Город'), ('ofc', 'ЦФЗ'), ('transport', 'Транспорт')], max_length=64, null=True, verbose_name='Тип')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Архивный файл',
                'verbose_name_plural': 'Архивные файлы',
                'ordering': ['-pk'],
            },
        ),
    ]
