# Generated by Django 4.1.3 on 2022-11-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_executor_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executorfile',
            options={'ordering': ['-pk'], 'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AddField(
            model_name='executorfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='executor_list_files', verbose_name='Файл со списком исполнителей'),
        ),
    ]
