# Generated by Django 4.1.3 on 2022-11-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_executorfile_options_executorfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExecutorFile',
        ),
        migrations.RemoveField(
            model_name='executor',
            name='code',
        ),
    ]
