# Generated by Django 4.1.3 on 2022-11-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_ofc_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='date_conclusion',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заключения'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='date_terminated',
            field=models.DateField(blank=True, null=True, verbose_name='Дата расторжения'),
        ),
    ]
