# Generated by Django 4.1.3 on 2022-11-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_executor_passport_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='gender',
            field=models.CharField(choices=[('NOT_CHOSEN', 'Не выбрано'), ('MALE', 'Мужской'), ('FEMALE', 'Женский')], default='NOT_CHOSEN', max_length=32, verbose_name='Пол'),
        ),
    ]
