# Generated by Django 4.1.3 on 2022-11-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_executor_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hour', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Часы')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='executor_hours', to='app.executor', verbose_name='Исполнитель')),
                ('ofc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='executor_hours', to='app.ofc', verbose_name='ЦФЗ')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='executor_hours', to='app.period', verbose_name='Период')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'ordering': ['-pk'],
            },
        ),
    ]
