# Generated by Django 4.1.3 on 2022-11-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_executorhours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executorhours',
            options={'ordering': ['-pk'], 'verbose_name': 'Часы исполнителя', 'verbose_name_plural': 'Часы исполнителя'},
        ),
        migrations.AlterField(
            model_name='archivefile',
            name='type',
            field=models.CharField(blank=True, choices=[('hours', 'Часы'), ('salary', 'Зарплата'), ('executor', 'Исполнитель'), ('city', 'Город'), ('ofc', 'ЦФЗ'), ('transport', 'Транспорт')], max_length=64, null=True, verbose_name='Тип'),
        ),
    ]
