# Generated by Django 4.1.3 on 2022-11-19 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_executorhour_delete_executorhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='executorhour',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_hours', to='app.archivefile', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='executorhour',
            name='role',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='executorhour',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_hours', to='app.day', verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='executorhour',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='executor_hours', to='app.executor', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='executorhour',
            name='hour',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Часы'),
        ),
        migrations.AlterField(
            model_name='executorhour',
            name='ofc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='executor_hours', to='app.ofc', verbose_name='ЦФЗ'),
        ),
        migrations.AlterField(
            model_name='executorhour',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='executor_hours', to='app.period', verbose_name='Период'),
        ),
    ]
