# Generated by Django 4.1.3 on 2022-11-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_day_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='final_date',
            field=models.DateField(blank=True, null=True, verbose_name='Конечная дата'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начальная дата'),
        ),
    ]
