# Generated by Django 4.1.3 on 2022-11-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_period_final_date_alter_period_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executorhour',
            name='hour',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Часы'),
        ),
    ]
