# Generated by Django 4.1.3 on 2022-11-19 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_executorhour_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hour', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Часы')),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_hours', to='app.day', verbose_name='День')),
            ],
            options={
                'verbose_name': 'Часы по дням',
                'verbose_name_plural': 'Часы по дням',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ExecutorHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=256, null=True, verbose_name='Роль')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='executor_hours', to='app.executor', verbose_name='Исполнитель')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_hours', to='app.archivefile', verbose_name='Файл')),
                ('ofc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='executor_hours', to='app.ofc', verbose_name='ЦФЗ')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='executor_hours', to='app.period', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Часы исполнителя',
                'verbose_name_plural': 'Часы исполнителя',
                'ordering': ['-pk'],
            },
        ),
        migrations.DeleteModel(
            name='ExecutorHour',
        ),
        migrations.AddField(
            model_name='dayhour',
            name='executor_hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_hours', to='app.executorhours', verbose_name='Часы по дням'),
        ),
    ]
