# Generated by Django 4.1.3 on 2022-11-19 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_dayhour_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
