# Generated by Django 4.1.3 on 2022-11-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_executor_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executor',
            name='uid',
        ),
    ]
