# Generated by Django 4.1.3 on 2022-11-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_executor_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivefile',
            name='status',
            field=models.CharField(choices=[('WAIT', 'Ожидание'), ('WARNING', 'Ожидание'), ('SUCCESS', 'Успешно'), ('ERROR', 'Ошибка'), ('NOT_STARTED', 'Не начато')], default='NOT_STARTED', max_length=64, verbose_name='Статус'),
        ),
    ]
