# Generated by Django 4.1.3 on 2022-11-23 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_archivefile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=256, verbose_name='Идентификатор')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='app.executor', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['-pk'],
            },
        ),
    ]
