# Generated by Django 4.1.3 on 2022-11-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Тип '),
        ),
        migrations.AlterField(
            model_name='contact',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='app.executor', verbose_name='Исполнитель'),
        ),
    ]
