# Generated by Django 4.1.3 on 2022-11-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_contact_type_alter_contact_executor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['type'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
