# Generated by Django 4.1.3 on 2022-11-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('curator', 'Куратор'), ('admin', 'Админ'), ('support', 'Тех. поддержка')], default='curator', max_length=64, verbose_name='Роль'),
        ),
    ]
