# Generated by Django 4.1.3 on 2022-12-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='executorhours',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_hours', to='app.transport'),
        ),
    ]
