# Generated by Django 4.1.3 on 2022-12-03 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_executorhours_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executors', to='app.transport', verbose_name='Транспорт'),
        ),
        migrations.AlterField(
            model_name='executorhours',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_hours', to='app.transport'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff', to='app.transport', verbose_name='Транспорт'),
        ),
    ]
