# Generated by Django 4.1.3 on 2022-12-03 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_executor_transport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executorhours',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_hours', to='app.executor', verbose_name='Исполнитель'),
        ),
    ]
