# Generated by Django 4.1.3 on 2022-12-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_executorhours_executor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executor',
            name='role',
        ),
        migrations.RemoveField(
            model_name='executorhours',
            name='role',
        ),
    ]
