# Generated by Django 4.1.3 on 2022-12-03 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_executor_role_remove_executorhours_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='bicycle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor', to='app.bicycle'),
        ),
    ]
