# Generated by Django 4.1.3 on 2022-12-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_executorhours_file_executorhours_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executorhours',
            old_name='file',
            new_name='files',
        ),
    ]
