# Generated by Django 4.1.3 on 2022-12-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_rename_file_executorhours_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivefile',
            name='type',
            field=models.CharField(blank=True, choices=[('hours', 'Часы'), ('salary', 'Зарплата'), ('executor', 'Исполнитель'), ('city', 'Город'), ('ofc', 'ЦФЗ'), ('transport', 'Транспорт'), ('phone', 'Номера тел.')], max_length=64, null=True, verbose_name='Тип'),
        ),
    ]
