# Generated by Django 4.1.3 on 2022-12-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_archivefile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='short_name',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Код города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название города'),
        ),
    ]
