# Generated by Django 4.1.3 on 2022-12-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_contact_identifier_alter_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('curator', 'Куратор'), ('admin', 'Админ'), ('support', 'Тех. поддержка'), ('accountant', 'Бухгалтер')], default='curator', max_length=64, verbose_name='Роль'),
        ),
    ]
