# Generated by Django 4.1.3 on 2022-12-28 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0050_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internship_hours', models.IntegerField(default=4)),
                ('initial_hours', models.IntegerField(default=50)),
                ('referral_executor_sum', models.IntegerField(default=3000)),
            ],
            options={
                'verbose_name': 'Конфиг исполнителей',
                'verbose_name_plural': 'Конфиг исполнителей',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CuratorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_for_internship', models.IntegerField(default=500, verbose_name='Оплата за стажировку')),
                ('payment_for_hours', models.IntegerField(default=2500, verbose_name='Оплата за часы')),
                ('curator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оплата куратору',
                'verbose_name_plural': 'Оплаты кураторам',
                'ordering': ['-pk'],
            },
        ),
    ]
