# Generated by Django 4.1.3 on 2022-12-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_curatorpayment_curator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curatorpayment',
            old_name='payment_for_hours',
            new_name='payment_for_initial_hours',
        ),
        migrations.RenameField(
            model_name='curatorpayment',
            old_name='payment_for_internship',
            new_name='payment_for_internship_hours',
        ),
    ]
