# Generated by Django 4.1.3 on 2022-12-29 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0053_rename_payment_for_hours_curatorpayment_payment_for_initial_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_for_internship_hours', models.IntegerField(default=500, verbose_name='Оплата за стажировку')),
                ('payment_for_initial_hours', models.IntegerField(default=2500, verbose_name='Оплата за часы')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оплата куратору',
                'verbose_name_plural': 'Оплаты кураторам',
                'ordering': ['-pk'],
            },
        ),
        migrations.DeleteModel(
            name='CuratorPayment',
        ),
    ]
