# Generated by Django 4.1.3 on 2022-12-29 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_userpayment_delete_curatorpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
