# Generated by Django 4.1.3 on 2022-12-29 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0055_userpayment_created_at_userpayment_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpayment',
            options={'ordering': ['-pk'], 'verbose_name': 'Сумма для выплат упр.персоналу', 'verbose_name_plural': 'Сумма для выплат упр.персоналу'},
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentForCurators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_for_internship_hours', models.IntegerField(default=500, verbose_name='Оплата за стажировку')),
                ('payment_for_initial_hours', models.IntegerField(default=2500, verbose_name='Оплата за часы')),
                ('is_paid', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=0)),
                ('initial_executors', models.ManyToManyField(related_name='initial_payments', to='app.executor')),
                ('internship_executors', models.ManyToManyField(related_name='internship_payments', to='app.executor')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.period', verbose_name='Период оплаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оплата кураторам по периодам',
                'verbose_name_plural': 'Оплата кураторам по периодам',
                'ordering': ['-pk'],
            },
        ),
    ]
