# Generated by Django 4.1.3 on 2022-12-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_remove_bicycle_code_bicycle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentforcurators',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
