# Generated by Django 4.1.3 on 2023-01-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_executor_internship_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivefile',
            name='type',
            field=models.CharField(blank=True, choices=[('hours', 'Часы'), ('salary', 'Зарплата'), ('executor', 'Исполнитель'), ('city', 'Город'), ('ofc', 'ЦФЗ'), ('transport', 'Транспорт'), ('phone', 'Номера тел.'), ('internship_samokat', 'Стажировка(САМОКАТ)')], max_length=64, null=True, verbose_name='Тип'),
        ),
    ]
